import { ReportData } from '../reportBuilder';
import { formatDuration, formatDate } from '../../utils/dateUtils';
import * as path from 'path';

const TYPE_EMOJI: Record<string, string> = {
  feature: '🟢',
  bugfix: '🔴',
  refactor: '🔵',
  docs: '📄',
  test: '🧪',
  chore: '⚙️',
  unknown: '⬜',
};

/**
 * Exports a ReportData object to a Markdown string.
 */
export function toMarkdown(report: ReportData): string {
  const lines: string[] = [];

  lines.push(`# ${report.period} — Work Report`);
  lines.push(`> Generated by CodeBrainPro`);
  lines.push(
    `> Period: ${formatDate(report.startDate)} → ${formatDate(report.endDate)}`,
  );
  lines.push('');

  // Achievement highlight
  if (report.narrative) {
    lines.push('## 🏆 Achievement Highlights');
    lines.push('');
    lines.push(`> ${report.narrative}`);
    lines.push('');
  }

  // Time summary
  lines.push('## ⏱ Time Summary');
  lines.push('');
  lines.push(
    `- **Total Active Time:** ${formatDuration(report.totalActiveMinutes)}`,
  );
  lines.push(`- **Lines Added:** ${report.linesAdded}`);
  lines.push(`- **Lines Removed:** ${report.linesRemoved}`);
  lines.push(`- **Total Commits:** ${report.commits.length}`);
  lines.push('');

  if (Object.keys(report.byDay).length > 0) {
    lines.push('### Daily Breakdown');
    lines.push('');
    lines.push('| Date | Active Time |');
    lines.push('| ---- | ----------- |');
    Object.entries(report.byDay)
      .sort(([a], [b]) => a.localeCompare(b))
      .forEach(([date, minutes]) => {
        lines.push(`| ${date} | ${formatDuration(minutes)} |`);
      });
    lines.push('');
  }

  // Work units
  if (report.workUnits.length > 0) {
    lines.push('## 📦 Work Units');
    lines.push('');
    report.workUnits.forEach((unit) => {
      const emoji = TYPE_EMOJI[unit.type] ?? '⬜';
      lines.push(`### ${emoji} ${unit.name} \`[${unit.type}]\``);
      lines.push(`- **Commits:** ${unit.commits.length}`);
      lines.push(`- **Repos:** ${unit.repos.join(', ')}`);
      lines.push(
        `- **Period:** ${formatDate(new Date(unit.startTime))} → ${formatDate(new Date(unit.endTime))}`,
      );
      lines.push(`- **Lines Changed:** ${unit.totalLinesChanged}`);
      lines.push('');
    });
  }

  // Repository breakdown
  if (Object.keys(report.repos).length > 0) {
    lines.push('## 🗂 Repository Breakdown');
    lines.push('');
    lines.push('| Repository | Active Time | Commits |');
    lines.push('| ---------- | ----------- | ------- |');
    Object.entries(report.repos).forEach(([repo, stats]) => {
      lines.push(
        `| ${repo} | ${formatDuration(stats.minutes)} | ${stats.commits} |`,
      );
    });
    lines.push('');
  }

  // Top files
  if (report.topFiles.length > 0) {
    lines.push('## 📁 Top Files');
    lines.push('');
    lines.push('| File | Edits |');
    lines.push('| ---- | ----- |');
    report.topFiles.forEach(({ filePath, editCount }) => {
      lines.push(`| \`${path.basename(filePath)}\` | ${editCount} |`);
    });
    lines.push('');
  }

  // Risk flags
  if (report.risks.length > 0) {
    lines.push('## ⚠️ Risk Flags');
    lines.push('');
    report.risks.forEach((risk) => {
      lines.push(
        `- **${risk.repoName}**: ${risk.linesChanged} uncommitted lines for ${risk.minutesSinceLastCommit}m (${risk.timestamp.slice(0, 10)})`,
      );
    });
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Generated at ${new Date().toISOString()}_`);

  return lines.join('\n');
}
